### ISSUE TITLE
Add ability to call attributes file (priority = medium)

### ISSUE THREAD

**Issue by sterobin** [pwright/pview#1]
(Reporting on behalf of Ben Hardesty)

@pwright , There's currently no way to specify an attributes file, so no attributes are resolved unless they're called explicitly in the file being previewed. Can we add support for specifying an attributes file? Better yet, a Pv2 repo will necessarily have a pantheon2.yml config file, which already contains the location of all the resources needed to build the docs, so would be good if we could possibly call that file as part of the command or in some other way. Or if it's easier, maybe we could add an "--all" option that used the pantheon2.yml file to build all assemblies in the repo or something?

**Comment by pwright** [comment]
@sterobin  With the latest push (0.0.6), I've removed yargs (now works with node 10) and pass all parameters to `asciidoctor`, so whatever you do with asciidoctor will work. Remember the goal here is packaging pantheon CSS/HAML. Any technique you can use with asciidoctor now works with pview, eg a script that creates a temp file that includes attributes and target adoc file will now work.. Leaving this issue open temporarily, because I don't believe this is what you want ;)

**Comment by sterobin** [comment]
@pwright Right, understood. And today asciidoc doesn't have any way to call the pv2 yaml file obviously and so makes writers have to wait until the content is imported into Pantheon2 itself in order to properly preview attributes. Of course we writers can do some shenanigans with symlinking and including of the yaml file or something to get it hard-coded at the top of the to-be-previewed file itself in real time just for the sake of verifying attributes. But it would sure be handy of part of this pview tool functionality was to also incorporate the yaml attributes so that by previewing, we mean truly previewing, including rendered attributes.

So in that way, it would be a step ahead of just a pv2 version of the vanilla asci preview. If that suggestion is too complicated or out of scope or whatnot, understood. But it would be a 20-ton cherry on top. :)

**Comment by sterobin** [comment]
@pwright In follow-up to our convo today, pasting below the example [pantheon2.yml](https://gitlab.cee.redhat.com/red-hat-managed-services-documentation/rhosak-documentation/-/blob/main/pantheon2.yml) contents for reference on how it incorporates attributes. Thanks.

Example `pantheon2.yml` contents
```
server: https://pantheon.corp.redhat.com
repository: rhosak-documentation
variants:
   - name: global-attributes
     path: _artifacts/attributes.adoc
     canonical: true
assemblies:
  - assemblies/*.adoc
  - assemblies/**/*.adoc
modules:
  - modules/*.adoc
  - modules/**/*.adoc
resources:
  - _images/**/*.png
  - _images/**/*.svg
```
